# .github/workflows/main.yml

name: Linter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout du code
        uses: actions/checkout@v4

      - name: â˜• Configuration de Java
        uses: actions/setup-java@v4
        with:
          # DÃ©finissez la version de Java utilisÃ©e par votre projet
          java-version: '24'
          distribution: 'temurin'
          cache: 'maven'

      - name: ğŸ“¦ Compilation, Tests et VÃ©rification (Linting)
        run: |
          echo "ExÃ©cution de la phase VERIFY de Maven..."
          mvn -B verify

      - name: ğŸ“„ Upload des Rapports (Tests & Checkstyle)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rapports-build
          path: target/